SLB-F1 create team
JujaLabs/teams-slack-bot pull request #13
Opened 2017-08-01 05:57 UTC by ivshapovalov

Without integreation and acceptance tests

2017-08-01 12:10 UTC, starikivan commented on src/main/java/ua/com/juja/microservices/teams/slackbot/model/Team.java
>  @ToString
@Data include @ToString

2017-08-01 12:53 UTC, ivshapovalov commented on src/main/java/ua/com/juja/microservices/teams/slackbot/model/Team.java
>  @ToString
Fixed: Replaced @Data by @Getter

2017-08-01 14:01 UTC, starikivan commented on src/main/java/ua/com/juja/microservices/teams/slackbot/model/TeamRequest.java
> +        if (members.size() == 0) {
Unnecessary check members.size() == 0

2017-08-02 11:10 UTC, petrokramar submitted a review, later dismissed

2017-08-03 21:49 UTC, OlgaKulikova requested changes

2017-08-03 21:49 UTC, OlgaKulikova commented on README.md
> + 2. Gradle build
Build application with Gradle

2017-08-03 21:49 UTC, OlgaKulikova commented on README.md
> + 4. For use FakeUserRepository (slackNames @a, @b, etc) instead of real UserRepository
"For" is useless word here. Please describe how to use fake repository instead of real one.

2017-08-03 21:49 UTC, OlgaKulikova commented on README.md
> + java -jar -Dspring.profiles.active=test teams-slack-bot.jar
use `such way` to write commands for the terminal

2017-08-03 21:49 UTC, OlgaKulikova commented on README.md
> + 7. Test your real slack
Test with your real slack

2017-08-03 21:49 UTC, OlgaKulikova commented on build.gradle
> +
weird deleting and adding empty strings. Without logic.

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/exceptions/ExceptionsHandler.java
> +    private void sendPostResponseAsRichMessage(String responseUrl, RichMessage richMessage) {
It's better to write private method or below the first method that invokes it or below all methods that invoke it.

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/exceptions/ExceptionsHandler.java
> +        sendPostResponseAsRichMessage(responseUrl, new RichMessage(ex.getMessage()));
you can invoke "sendPostResponseAsRichMessage(ex.getMessage())"
and in that method you can take the responseUrl as a class field and create new RichMessage.

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/exceptions/ExceptionsHandler.java
> +        sendPostResponseAsRichMessage(responseUrl, new RichMessage(ex.getMessage()));
in others methods the same

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/exceptions/ExceptionsHandler.java
> +            message = replaceUuidsBySlackNamesInMessage(ex.getError().getExceptionMessage());
"ex.getError()" is invoked three times. Use local variable.

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/exceptions/ExceptionsHandler.java
> +        String[] array = message.split("#");
the name of array "array" is not good. Try "messageParts" or "parts".

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/exceptions/ExceptionsHandler.java
> +            Set<String> slackNames=new HashSet<>();
add spaces around operator

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/exceptions/ExceptionsHandler.java
> +        return message;
I think this method shoud live in Util class.

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/model/Team.java
> +    public Set<String> getMembers() {
why we need two different approches to create getters?

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/model/User.java
> -    private String uuid;
why not private?

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/repository/impl/AbstractRestRepository.java
> +    HttpHeaders setupBaseHttpHeaders() {
why not public?

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/repository/impl/AbstractRestRepository.java
> +class AbstractRestRepository {
why not public?

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/repository/impl/RestTeamRepository.java
> +    private String restApiVersion="v1";
why you write "v1" if you use @Value

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/repository/impl/RestTeamRepository.java
> +        return null;
please add //TODO for future implementations.

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/repository/impl/RestUserRepository.java
> +        }
this converting should be in Util class

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/repository/impl/RestUserRepository.java
> +        List<User> users;
It's redundant to anounce list here and assing below. Do it in one string.

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/repository/impl/RestUserRepository.java
> +    private String userUrlFindUsersByUuids;
what about version part of url?

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/repository/impl/RestUserRepository.java
> +        log.debug("Started creating userUuidsRequest and HttpEntity");
two debug logs one by one - redundant

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/repository/impl/RestUserRepository.java
> +        List<User> users;
the same as above

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/repository/impl/RestUserRepository.java
> +                    ());
check if this braces in another string? should be next to the method's name

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/service/TeamService.java
> +@Service
As I know such annotation should be only above conrete classes but if I'm wrong - proove it.

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/service/impl/SlackNameHandlerService.java
> +        Set<User> usersDTO = new HashSet<>(userService.findUsersBySlackNames(slackNames));
please it should be or `Set<User> users` or `Set<UserDto> usersDto`

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/service/impl/SlackNameHandlerService.java
> +
the whole this class wants someone to separate util functions and move them to Util class and only business logic should be left.

2017-08-03 21:49 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/service/impl/TeamSlackbotServiceImpl.java
> +}
I think a TeamService and TeamSlackBotService - is excessive separation. It could be in one service class.

2017-08-04 04:33 UTC, asidun requested changes

2017-08-04 04:33 UTC, asidun commented on src/main/java/ua/com/juja/microservices/teams/slackbot/controller/TeamSlackbotController.java
> +        if (!isTokenCorrect(token, fromUser, response)) {
Better change if condition without NOT. And then if block will continue until the end of the method. I think this is more common rule.

2017-08-04 04:33 UTC, asidun commented on src/main/java/ua/com/juja/microservices/teams/slackbot/controller/TeamSlackbotController.java
> +        sendFirstResponseMessage(response, ACTIVATE_TEAM_MESSAGE, HttpServletResponse.SC_OK);
sendFirstResponseMessage - the bad name of the method. I do not understand what method to do.

2017-08-04 04:33 UTC, asidun commented on src/main/java/ua/com/juja/microservices/teams/slackbot/controller/TeamSlackbotController.java
> +        log.debug("Started send last response message to slack '{}' ", message.getText());
"last response message" is not so good name. During reading the debug information, a developer can be confused.

2017-08-04 04:33 UTC, asidun commented on src/main/java/ua/com/juja/microservices/teams/slackbot/controller/TeamSlackbotController.java
> +    private boolean isTokenCorrect(@RequestParam("token") String token, @RequestParam("user_name") String fromUser,
May be rename to isTokenCorrectforAcrivateTeam. Because in log.warn you write about command 'Activate team'. Or change log.warn message

2017-08-04 04:33 UTC, asidun commented on src/main/java/ua/com/juja/microservices/teams/slackbot/controller/TeamSlackbotController.java
> +        sendFirstResponseMessage(response, ACTIVATE_TEAM_MESSAGE, HttpServletResponse.SC_OK);
may be rename to sendResponseMessage

2017-08-04 04:33 UTC, asidun commented on src/main/java/ua/com/juja/microservices/teams/slackbot/repository/impl/AbstractRestRepository.java
> +    HttpHeaders setupBaseHttpHeaders() {
Why did you reduce the scope of the method?

2017-08-04 04:33 UTC, asidun commented on src/main/java/ua/com/juja/microservices/teams/slackbot/repository/impl/FakeUserRepository.java
> +package ua.com.juja.microservices.teams.slackbot.repository.impl;
Is this method used for tests only? May be it should be placed in test package?

2017-08-04 05:59 UTC, ivshapovalov commented on src/main/java/ua/com/juja/microservices/teams/slackbot/repository/impl/FakeUserRepository.java
> +package ua.com.juja.microservices.teams.slackbot.repository.impl;
Impossible to run application with bean in test package. Spring don't find bean there. 
java -jar -Dspring.profiles.active=test teams-slack-bot.jar

2017-08-07 18:33 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/exceptions/ExceptionsHandler.java
>          log.debug("Start find and replace uuids by slackNames in message {}", message);
I think this method shouldn't be in Exception handler but in some service.

2017-08-07 18:33 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/util/SlackNameHandler.java
> +@Service
Если это типа утилитного класса, то аннотация @Service не нужна. Его не нужно инжектить, так как методы в нем статические. Проверь все.

2017-08-07 18:33 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/util/SlackNameHandler.java
> +        log.debug("Finished extract slackNames '{}' from text '{}", slackNames.toString(), text);
please delete this one log. The next row do the same.

2017-08-07 18:33 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/slackbot/util/Utils.java
> +    public static void addAtToSlackNames(List<String> slackNames) {
SlackNameHandler class suits better for this method.

2017-08-08 18:19 UTC, OlgaKulikova approved these changes

2017-08-09 08:31 UTC, OlgaKulikova requested changes

2017-08-09 08:31 UTC, OlgaKulikova commented on src/main/resources/application.properties
> +spring.profiles.active=production
Please do changes:
rest.api.version=v1

#Teams microservice
teams.baseURL=http://teams
endpoint.activateTeam=/teams
endpoint.deactivateTeam=/teams/users
endpoint.getTeam=/teams/users

#Users microservices
user.baseURL=http://users
endpoint.usersBySlackNames=/users/usersBySlackNames
endpoint.usersByUuids=/users/usersByUuids

slack.slashCommandToken=slashCommandToken
server.port=8091
spring.profiles.active=production

2017-08-09 10:04 UTC, OlgaKulikova approved these changes

2017-08-11 11:57 UTC, asidun approved these changes

2017-08-11 11:58 UTC, merged